(defconst sea-logo (expand-file-name
		    (if (display-graphic-p) "logo.png" "banner.txt")
		    sea-etc-dir)
  "Set logo. nil means official logo.")
;; (require 'init-package)
(require 'init-straight)

(require 'init-core)
(require 'init-utils)
(require 'init-yasnippet)

(require 'init-better-defaults)
(require 'init-projectile)
(require 'init-dired)

(require 'init-evil)
(require 'init-keybindings)
(require 'init-lookup)
(require 'init-ui)
(when (display-graphic-p)
  (require 'init-font))
(require 'init-modeline)
(require 'init-highlight)
;; (require 'init-ivy)
(require 'init-pyim)
(require 'init-vertico)
(require 'init-corfu)

(require 'init-ai)
(require 'init-hydra)
(require 'init-folding)
(require 'init-flycheck)
(require 'init-vcs)

(require 'init-treemacs)
;; (require 'init-treesitter)
(require 'init-lsp)
(require 'init-org)
(require 'init-py)
(require 'init-go)
(require 'init-rust)
(require 'init-web)


(setq custom-file (concat user-emacs-directory "custom.el"))
(load custom-file t t)
(dolist (dir (list sea-cache-dir sea-etc-dir))
  (unless (file-directory-p dir)
    (make-directory dir t)))
